## YAML Template.
#installation d'Apache sur le serveur dev
- name: Installation d'Apache
  hosts: all
  tasks:
    - name: Inscrire le nouveau dépôt
      apt_repository:
        repo: deb http://ftp.fr.debian.org/debian/ stretch main
        state: present
        update_cache: yes
    - name: Installation d'apache2
      apt:
        name: apache2
        state: present
    - name: Installation de ca-certificates
      apt:
        name: ca-certificates
        state: present
    - name: Installation de apt-transport-https
      apt:
        name: apt-transport-https
        state: present
    - name: Démarrer le service Apache
      service:
        name: apache2
        state: started
        enabled: yes
        
    # INSTALLATION DE PHP
          
    - name: Enregistrer la clé
      apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: present
    - name: Inscrire le nouveau dépôt
      apt_repository:
        repo: deb https://packages.sury.org/php/ stretch main
        state: present
        update_cache: yes
    - name: Installation de PHP
      apt :
        name: php7.2
        state: present
        
# INSTALLATION MYSQL
    
- name: Installation de MySQL
  hosts: all
  tasks:
    - name: Installation de python-pip
      apt:
        name: python-pip
        state: present
    - name: Installer le module Python pour MySQL
      pip:
        name: PyMySQL
    - name: Installation de python-mysqldb
      apt:
        name: python-mysqldb
        state: present
    - name: Installation de mysql-server
      apt:
        name: mysql-server
        state: present
    - name: Gestion du my.cnf
      copy:
          src: /root/autres/my.cnf.j2
          dest: /root/.my.cnf
          owner: root
          group: root
          mode: 0600
    - name: Redémarrer le service MySQL
      service:
        name: mysql
        state: started
        enabled: yes
    - name: Gestion du mot de passe du root
      mysql_user:
          name: root
          password: epsi
          login_unix_socket: /var/run/mysqld/mysqld.sock
    - name: Création de la base de données
      mysql_db:
          name: "{{mysql_db}}"
          state: present
          login_unix_socket: /var/run/mysqld/mysqld.sock
    - name: Création de l'utilisateur élève et affectation des privilèges sur une base de données
      mysql_user:
          name: "{{mysql_user}}"
          password: "{{mysql_password}}"
          host: localhost
          priv: "{{mysql_db}}.*:ALL,GRANT"
          login_unix_socket: /var/run/mysqld/mysqld.sock

# CONFIG PHPMYADMIN

- name: Installation de PHPMyAdmin
  hosts: all
  tasks:
    - name: Installation de debconf
      apt:
          name: debconf-utils
          state: present
    - name: Installation de dbconfig
      debconf:
          name: phpmyadmin
          question: phpmyadmin/dbconfig-install
          value: true
          vtype: boolean
    - name: Installation de dbconfig - Partie 2
      debconf:
          name: phpmyadmin
          question: phpmyadmin/app-password-confirm
          value: "{{mysql_password}}"
          vtype: password
    - name: Installation de dbconfig - Partie 3
      debconf:
          name: phpmyadmin
          question: phpmyadmin/mysql/admin-pass
          value: "{{mysql_password}}"
          vtype: password
    - name: Installation de dbconfig - Partie 4
      debconf:
          name: phpmyadmin
          question: phpmyadmin/mysql/app-pass
          value: "{{mysql_password}}"
          vtype: password
    - name: Installation de dbconfig - Partie 5
      debconf:
          name: phpmyadmin
          question: phpmyadmin/reconfigure-webserver
          value: apache2
          vtype: multiselect
    - name: Installation de phpmyadmin
      apt:
          name: phpmyadmin
          state: present
    - name: Redémarrer Apache
      service:
          name: apache2
          state: started
          enabled: yes
          
- name: Gestion des erreurs
  hosts: all
  tasks:
    - name: Suppression de index.html
      file:
          path: /var/www/html/index.html
          state: absent
    - name: Copie d'index.php
      copy:
          src: /root/index.php
          dest: /var/www/html/index.php
          owner: www-data
          group: www-data
          mode: 0755