## YAML Template.
#installation d'Apache sur le serveur dev
- name: Installation d'Apache
  hosts: all
  tasks:
      - name: Inscrire le nouveau dépôt
        apt_repository:
            repo: deb http://ftp.fr.debian.org/debian stretch main
            state: present
            update_cache: yes
      - name: Installation d'apache2
        apt :
            name: apache2,ca-certificates,apt-transport-https
            state: present
      - name: Démarrer le service Apache
        service:
            name: apache2
            state: started
            enabled: yes