## YAML Template.
#installation d'Apache sur le serveur dev
- name: Installation d'Apache
  hosts: all
  tasks:
    - name: Inscrire le nouveau dépôt
      apt_repository:
        repo: deb http://ftp.fr.debian.org/debian/ stretch main
        state: present
        update_cache: yes
    - name: Installation d'apache2
      apt:
        name: apache2
        state: present
    - name: Installation de ca-certificates
      apt:
        name: ca-certificates
        state: present
    - name: Installation de apt-transport-https
      apt:
        name: apt-transport-https
        state: present
    - name: Démarrer le service Apache
      service:
        name: apache2
        state: started
        enabled: yes
        
    # INSTALLATION DE PHP
          
    - name: Enregistrer la clé
      apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: present
    - name: Inscrire le nouveau dépôt
      apt_repository:
        repo: deb https://packages.sury.org/php/ stretch main
        state: present
        update_cache: yes
    - name: Installation de PHP
      apt :
        name: php7.2
        state: present