## YAML Template.
#installation d'Apache sur le serveur dev
- name: Installation d'Apache
  hosts: all
  tasks:
    - name: Inscrire le nouveau dépôt
      apt_repository:
        repo: deb http://ftp.fr.debian.org/debian/ stretch main
        state: present
        update_cache: yes
    - name: Installation d'apache2
      apt:
        name: apache2
        state: present
    - name: Installation de ca-certificates
      apt:
        name: ca-certificates
        state: present
    - name: Installation de apt-transport-https
      apt:
        name: apt-transport-https
        state: present
    - name: Démarrer le service Apache
      service:
        name: apache2
        state: started
        enabled: yes
        
    # INSTALLATION DE PHP
          
    - name: Enregistrer la clé
      apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: present
    - name: Inscrire le nouveau dépôt
      apt_repository:
        repo: deb https://packages.sury.org/php/ stretch main
        state: present
        update_cache: yes
    - name: Installation de PHP
      apt :
        name: php7.2
        state: present
        
# INSTALLATION MYSQL
    
- name: Installation de MySQL
  hosts: all
  tasks:
    - name: Inscrire le nouveau dépôt
      apt_repository:
        repo: deb http://ftp.fr.debian.org/debian/ stretch main
        state: present
        update_cache: yes
    - name: Installation de python-pip
      apt:
        name: python-pip
        state: present
    - name: Installer le module Python pour MySQL
      pip:
        name: PyMySQL
    - name: Installation de python-mysqldb
      apt:
        name: python-mysqldb
        state: present
    - name: Installation de mysql-server
      apt:
        name: mysql-server
        state: present
    - name: Gestion du my.cnf
      copy:
          src: /root/autres/my.cnf.j2
          dest: /root/.my.cnf
          owner: root
          group: root
          mode: 0600
    - name: Redémarrer le service MySQL
      service:
        name: mysql
        state: restarted
        enabled: yes
    - name: Gestion du mot de passe du root
      mysql_user:
          name: root
          password: epsi
          login_unix_socket: /var/run/mysqld/mysqld.sock